### PR TITLE
Log with queue

### PR DESCRIPTION
**Pull request by aryala7**
# Description

this feature adds with_queue key value to config. which if it set true it simply store logs in the database using jobs.
this prevent extra loading time if you have a big dataset.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Any relevant logs, error output, etc?

...

## Any other comments?

...

# Checklist

- [ ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by bilfeldt — CHANGES_REQUESTED** [review]
Thanks for this PR @aryala7 👍 

Do you mind providing a test for this?

**Comment by aryala7** [comment]
> Thanks for this PR @aryala7 👍
> 
> Do you mind providing a test for this?
`

**Comment by aryala7** [comment]
@bilfeldt tests were implemented. [c927b1b](https://github.com/bilfeldt/laravel-route-statistics/pull/19/commits/c927b1b26b3a94764d1fca38b329463aef397222)

**Comment by aryala7** [comment]
@bilfeldt may you check this PR out? is there problem with it?

**Comment by bilfeldt** [comment]
Thanks for the update @aryala7 

I will have a look at it during beginning of next week and check if this is something we can merge. Probably I will update the tests a bit.

**Comment by aryala7** [comment]
@bilfeldt hey body. any chance to accept the PR?

**Comment by bilfeldt** [comment]
@aryala7 with the current solution the job is hardcoded and cannot be altered by the user in any way possible. I would like it be extendable do you have any suggestions?

The main problem is that the `RequestLoggerInterface` require an instance of the `Request` but that is not serializable, so we cannot pass that to the queued job.

Hence we need to extract the needed data from the request and pass that data to the job. That means that the job will *not* be implementing the `RequestLoggerInterface`.

**Comment by aryala7** [comment]
@bilfeldt I'm sorry but i don't get the **RequestLoggerInterface** problem. It would be great if you explain it a bit clearer but for the hardcoded job I can add an array to the config file. So user can change the connection of job, tags and other available settings related to queues in Laravel.

**Review by bilfeldt — APPROVED** [review]

**Comment by bilfeldt** [comment]
@aryala7 I am okay with the job not being configurable at the moment. I don't think we should add a ton of extra configurations. At the end the user can always just override the `log` method.

I have updated the tests a bit and added a new function for getting the logging attributes.

This is a good addition to the package. Thanks for your contribution 👍

**Pull request merged**
